import { ThemeConfig, ThemeName } from '@/types/wedding';

export const themes: Record<ThemeName, ThemeConfig> = {
  // ===== NEW PREMIUM TEMPLATES =====

  'royal-gold': {
    name: 'royal-gold',
    label: 'Royal Gold',
    labelAr: 'ذهبي ملكي',
    colors: {
      primary: '#C9A84C',
      secondary: '#152040',
      background: '#0A0F1E',
      text: '#F5E6C8',
      button: '#C9A84C',
      accent: '#E0C878',
    },
    fontClass: 'font-serif',
    description: 'فخامة الفنادق الملكية',
    previewGradient: 'linear-gradient(135deg, #0A0F1E 0%, #152040 40%, #0A0F1E 100%)',
    layoutStyle: 'classic',
    heroStyle: 'cinematic',
    sectionSpacing: 'compact',
    showPattern: true,
    patternType: 'arabesque',
    ornamentStyle: 'bold',
    cornerOrnaments: true,
    fontScale: 1.15,
  },

  'luxury-dark': {
    name: 'luxury-dark',
    label: 'Luxury Dark',
    labelAr: 'داكن فاخر',
    colors: {
      primary: '#D4AF37',
      secondary: '#111111',
      background: '#050505',
      text: '#E8E0D0',
      button: '#D4AF37',
      accent: '#F0E6C8',
    },
    fontClass: 'font-sans',
    description: 'سينمائي أسود وذهبي',
    previewGradient: 'linear-gradient(135deg, #050505 0%, #111111 40%, #050505 100%)',
    layoutStyle: 'modern',
    heroStyle: 'split',
    sectionSpacing: 'compact',
    showPattern: true,
    patternType: 'lines',
    ornamentStyle: 'none',
    cornerOrnaments: false,
    fontScale: 0.9,
  },

  'floral-romance': {
    name: 'floral-romance',
    label: 'Floral Romance',
    labelAr: 'رومانسية زهور',
    colors: {
      primary: '#C4788A',
      secondary: '#FFE8E8',
      background: '#FFF5F5',
      text: '#4A3040',
      button: '#C4788A',
      accent: '#D4A0A7',
    },
    fontClass: 'font-serif',
    description: 'أناقة ورمانسية الزهور',
    previewGradient: 'linear-gradient(135deg, #FFF5F5 0%, #FFE8E8 40%, #FFF5F5 100%)',
    layoutStyle: 'romantic',
    heroStyle: 'centered',
    sectionSpacing: 'normal',
    showPattern: true,
    patternType: 'floral',
    ornamentStyle: 'subtle',
    cornerOrnaments: false,
    fontScale: 1.0,
  },

  'arabic-heritage': {
    name: 'arabic-heritage',
    label: 'Arabic Heritage',
    labelAr: 'تراث عربي',
    colors: {
      primary: '#C9A84C',
      secondary: '#153025',
      background: '#0A1A15',
      text: '#F0E6D3',
      button: '#C9A84C',
      accent: '#E0C878',
    },
    fontClass: 'font-serif',
    description: 'أنماط عربية وأصالة',
    previewGradient: 'linear-gradient(135deg, #0A1A15 0%, #153025 40%, #0A1A15 100%)',
    layoutStyle: 'traditional',
    heroStyle: 'frame',
    sectionSpacing: 'normal',
    showPattern: true,
    patternType: 'arabesque',
    ornamentStyle: 'bold',
    cornerOrnaments: true,
    fontScale: 1.15,
  },

  'minimal-modern': {
    name: 'minimal-modern',
    label: 'Minimal Modern',
    labelAr: 'عصري بسيط',
    colors: {
      primary: '#1A1A1A',
      secondary: '#F0F0F0',
      background: '#FAFAFA',
      text: '#1A1A1A',
      button: '#1A1A1A',
      accent: '#333333',
    },
    fontClass: 'font-sans',
    description: 'فخامة عصرية بسيطة',
    previewGradient: 'linear-gradient(135deg, #FAFAFA 0%, #F0F0F0 40%, #FAFAFA 100%)',
    layoutStyle: 'minimal',
    heroStyle: 'centered',
    sectionSpacing: 'compact',
    showPattern: false,
    patternType: undefined,
    ornamentStyle: 'none',
    cornerOrnaments: false,
    fontScale: 0.9,
  },

  // ===== EXISTING TEMPLATES =====

  'classic-gold': {
    name: 'classic-gold',
    label: 'Classic Gold',
    labelAr: 'ذهبي كلاسيكي',
    colors: {
      primary: '#D4A853',
      secondary: '#1A1A2E',
      background: '#0D0D1A',
      text: '#FFFFFF',
      button: '#D4A853',
      accent: '#E8C874',
    },
    fontClass: 'font-serif',
    description: 'أناقة ذهبية كلاسيكية',
    previewGradient: 'linear-gradient(135deg, #0D0D1A 0%, #1A1A2E 40%, #0D0D1A 100%)',
    layoutStyle: 'classic',
    heroStyle: 'centered',
    sectionSpacing: 'spacious',
    showPattern: true,
    patternType: 'geometric',
    ornamentStyle: 'gold',
    cornerOrnaments: true,
    fontScale: 1.1,
  },

  'modern-dark': {
    name: 'modern-dark',
    label: 'Modern Dark',
    labelAr: 'داكن عصري',
    colors: {
      primary: '#C0C0C0',
      secondary: '#1A1A1A',
      background: '#0A0A0A',
      text: '#E0E0E0',
      button: '#C0C0C0',
      accent: '#FFFFFF',
    },
    fontClass: 'font-sans',
    description: 'عصرية وفخامة',
    previewGradient: 'linear-gradient(135deg, #0A0A0A 0%, #1A1A1A 40%, #0A0A0A 100%)',
    layoutStyle: 'modern',
    heroStyle: 'split',
    sectionSpacing: 'compact',
    showPattern: true,
    patternType: 'lines',
    ornamentStyle: 'none',
    cornerOrnaments: false,
    fontScale: 0.9,
  },

  'elegant-white': {
    name: 'elegant-white',
    label: 'Elegant White',
    labelAr: 'أبيض أنيق',
    colors: {
      primary: '#8B7355',
      secondary: '#F5F0EB',
      background: '#FFFFFF',
      text: '#2C2C2C',
      button: '#8B7355',
      accent: '#A0926B',
    },
    fontClass: 'font-serif',
    description: 'نقاء وأناقة',
    previewGradient: 'linear-gradient(135deg, #FFFFFF 0%, #F5F0EB 40%, #FFFFFF 100%)',
    layoutStyle: 'ornate',
    heroStyle: 'frame',
    sectionSpacing: 'normal',
    showPattern: true,
    patternType: 'floral',
    ornamentStyle: 'subtle',
    cornerOrnaments: true,
    fontScale: 1.0,
  },

  'royal-blue': {
    name: 'royal-blue',
    label: 'Royal Blue',
    labelAr: 'أزرق ملكي',
    colors: {
      primary: '#C9A84C',
      secondary: '#1B2A4A',
      background: '#0F1B33',
      text: '#F0E6D3',
      button: '#C9A84C',
      accent: '#E0C878',
    },
    fontClass: 'font-serif',
    description: 'فخامة ملكية',
    previewGradient: 'linear-gradient(135deg, #0F1B33 0%, #1B2A4A 40%, #0F1B33 100%)',
    layoutStyle: 'classic',
    heroStyle: 'cinematic',
    sectionSpacing: 'normal',
    showPattern: true,
    patternType: 'arabesque',
    ornamentStyle: 'bold',
    cornerOrnaments: true,
    fontScale: 1.1,
  },

  'rose-gold': {
    name: 'rose-gold',
    label: 'Rose Gold',
    labelAr: 'ذهبي وردي',
    colors: {
      primary: '#B76E79',
      secondary: '#2D1F22',
      background: '#1A1215',
      text: '#F5E6E8',
      button: '#B76E79',
      accent: '#D4A0A7',
    },
    fontClass: 'font-sans',
    description: 'رمانسية ودافئة',
    previewGradient: 'linear-gradient(135deg, #1A1215 0%, #2D1F22 40%, #1A1215 100%)',
    layoutStyle: 'romantic',
    heroStyle: 'centered',
    sectionSpacing: 'normal',
    showPattern: true,
    patternType: 'floral',
    ornamentStyle: 'subtle',
    cornerOrnaments: false,
    fontScale: 1.05,
  },

  'traditional-arabic': {
    name: 'traditional-arabic',
    label: 'Traditional Arabic',
    labelAr: 'عربي تقليدي',
    colors: {
      primary: '#2E7D32',
      secondary: '#1B5E20',
      background: '#0D3B0F',
      text: '#FFFFFF',
      button: '#2E7D32',
      accent: '#4CAF50',
    },
    fontClass: 'font-serif',
    description: 'تراث وأصالة',
    previewGradient: 'linear-gradient(135deg, #0D3B0F 0%, #1B5E20 40%, #0D3B0F 100%)',
    layoutStyle: 'traditional',
    heroStyle: 'frame',
    sectionSpacing: 'spacious',
    showPattern: true,
    patternType: 'arabesque',
    ornamentStyle: 'bold',
    cornerOrnaments: true,
    fontScale: 1.15,
  },
};

export function getTheme(themeName: ThemeName): ThemeConfig {
  return themes[themeName] || themes['classic-gold'];
}

export function getThemeColors(themeName: ThemeName) {
  const theme = getTheme(themeName);
  return theme.colors;
}

export const themeOptions = Object.values(themes).map(t => ({
  value: t.name,
  label: t.label,
  labelAr: t.labelAr,
  description: t.description,
  colors: t.colors,
  previewGradient: t.previewGradient,
}));
